version: '0.1'

services:
  keystore:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    user: "0" 
    volumes:
      - ./secrets:/secrets:z
      - ./setup:/setup:z
    command: bash /setup/setup-keystore.sh
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}


  certs:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
      - ./secrets:/secrets:z
      - ./setup:/setup:z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
